import streamlit as st
import random
import base64
from PIL import Image, ImageDraw
import io
import time

# Configuration de la page
st.set_page_config(
    page_title="🌊 Tsunami Expert", 
    page_icon="🌊", 
    layout="wide"
)

# ==================== STYLE MODERNE ====================
st.markdown("""
<style>
    .main-header {
        font-size: 2.8rem;
        color: #1e88e5;
        text-align: center;
        margin-bottom: 1rem;
        font-weight: bold;
    }
    .chat-container {
        background: white;
        padding: 25px;
        border-radius: 15px;
        margin-bottom: 20px;
        border: 1px solid #e0e0e0;
        box-shadow: 0 4px 15px rgba(0,0,0,0.1);
    }
    .sidebar-content {
        background: #f8f9fa;
        padding: 20px;
        border-radius: 12px;
        margin: 12px 0;
        border-left: 4px solid #1e88e5;
    }
    .emergency-box {
        background: linear-gradient(135deg, #ff5252, #d32f2f);
        color: white;
        padding: 18px;
        border-radius: 12px;
        text-align: center;
        font-weight: bold;
    }
    .question-btn {
        background: linear-gradient(135deg, #4caf50, #2e7d32);
        color: white;
        border: none;
        padding: 12px 18px;
        border-radius: 10px;
        margin: 6px 0;
        width: 100%;
        cursor: pointer;
        transition: all 0.3s;
        font-weight: 600;
        font-size: 0.9em;
        text-align: left;
    }
    .question-btn:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 12px rgba(76,175,80,0.3);
    }
    .arabic-text {
        direction: rtl;
        text-align: right;
        line-height: 1.8;
        font-size: 1.05em;
    }
    .category-header {
        color: #1e88e5;
        border-bottom: 2px solid #1e88e5;
        padding-bottom: 8px;
        margin-top: 20px;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)

# ==================== SYSTÈME MULTILINGUE ====================

LANGUAGES = {
    "🇫🇷 Français": "fr",
    "🇬🇧 English": "en", 
    "🇸🇦 العربية": "ar"
}

# ==================== BASE DE CONNAISSANCES COMPLÈTE ====================

KNOWLEDGE_BASE = {
    # ========== DÉFINITION ET CAUSES ==========
    "definition_tsunami": {
        "keywords": {
            "fr": ["définition", "qu'est-ce", "c'est quoi", "explique", "définir", "quoi", "tsunami"],
            "en": ["definition", "what is", "explain", "define", "what", "tsunami"],
            "ar": ["تعريف", "ما هو", "شرح", "ماهو", "ما", "تسونامي"]
        },
        "responses": {
            "fr": """
**🌊 DÉFINITION DU TSUNAMI**

Un **tsunami** (mot japonais signifiant "vague du port") est une série de vagues océaniques extrêmement longues générées par le déplacement soudain d'un grand volume d'eau.

**Caractéristiques principales :**
- **Vitesse** : 500-800 km/h en eau profonde (comme un avion de ligne)
- **Hauteur** : 30 cm à 1m en mer → 10-30m près des côtes
- **Longueur d'onde** : 100-200 km (vs 100m pour une vague normale)
- **Période** : 10-60 minutes entre les vagues successives

**Mécanisme physique :** Le déplacement vertical du fond marin pousse toute la colonne d'eau, créant des ondes qui se propagent dans toutes les directions.
            """,
            "en": """
**🌊 TSUNAMI DEFINITION**

A **tsunami** (Japanese for "harbor wave") is a series of extremely long ocean waves generated by the sudden displacement of a large volume of water.

**Key characteristics:**
- **Speed**: 500-800 km/h in deep water (like a jet airliner)
- **Height**: 30 cm to 1m at sea → 10-30m near coasts
- **Wavelength**: 100-200 km (vs 100m for normal wave)
- **Period**: 10-60 minutes between successive waves

**Physical mechanism**: Vertical seabed displacement pushes the entire water column, creating waves that propagate in all directions.
            """,
            "ar": """
**🌊 تعريف التسونامي**

**التسونامي** (كلمة يابانية تعني "موجة الميناء") هو سلسلة من أمواج المحيط الطويلة جدًا الناتجة عن الانزياح المفاجئ لحجم كبير من الماء.

**الخصائص الرئيسية:**
- **السرعة**: 500-800 كم/ساعة في المياه العميقة (مثل الطائرة النفاثة)
- **الارتفاع**: 30 سم إلى 1م في البحر → 10-30م بالقرب من السواحل
- **الطول الموجي**: 100-200 كم (مقابل 100م للموجة العادية)
- **الفترة**: 10-60 دقيقة بين الأمواج المتتالية

**الآلية الفيزيائية**: الانزياح الرأسي لقاع البحر يدفع عمود الماء بالكامل، مكونًا موجات تنتشر في جميع الاتجاهات.
            """
        }
    },
    
    "difference_vague_tsunami": {
        "keywords": {
            "fr": ["différence", "comparaison", "vague normale", "vague vs tsunami", "différent"],
            "en": ["difference", "compare", "normal wave", "wave vs tsunami", "different"],
            "ar": ["فرق", "مقارنة", "موجة عادية", "موجة مقابل تسونامي", "مختلف"]
        },
        "responses": {
            "fr": """
**🌊 DIFFÉRENCE ENTRE TSUNAMI ET VAGUE NORMALE**

| Caractéristique | Vague Normale | Tsunami |
|-----------------|---------------|---------|
| **Cause** | Vent | Séisme/Glissement |
| **Longueur d'onde** | 100-200 m | 100-200 km |
| **Vitesse** | 10-60 km/h | 500-800 km/h |
| **Période** | 5-20 secondes | 10-60 minutes |
| **Énergie** | Surface | Colonne d'eau entière |
| **Comportement** | Brise sur plage | Inonde terres |

**Point crucial :** Une vague normale ne déplace que l'eau de surface, tandis qu'un tsunami déplace TOUTE la colonne d'eau du fond à la surface.
            """,
            "en": """
**🌊 DIFFERENCE BETWEEN TSUNAMI AND NORMAL WAVE**

| Characteristic | Normal Wave | Tsunami |
|----------------|-------------|---------|
| **Cause** | Wind | Earthquake/Landslide |
| **Wavelength** | 100-200 m | 100-200 km |
| **Speed** | 10-60 km/h | 500-800 km/h |
| **Period** | 5-20 seconds | 10-60 minutes |
| **Energy** | Surface | Entire water column |
| **Behavior** | Breaks on beach | Floods inland |

**Key point:** A normal wave only moves surface water, while a tsunami moves the ENTIRE water column from bottom to surface.
            """,
            "ar": """
**🌊 الفرق بين التسونامي والموجة العادية**

| الخاصية | الموجة العادية | التسونامي |
|----------|----------------|-----------|
| **السبب** | الرياح | الزلزال/الانهيار |
| **الطول الموجي** | 100-200 م | 100-200 كم |
| **السرعة** | 10-60 كم/ساعة | 500-800 كم/ساعة |
| **الفترة** | 5-20 ثانية | 10-60 دقيقة |
| **الطاقة** | السطح | عمود الماء بالكامل |
| **السلوك** | ينكسر على الشاطئ | يغمر اليابسة |

**النقطة الأساسية:** الموجة العادية تحرك فقط مياه السطح، بينما التسونامي يحرك عمود الماء بالكامل من القاع إلى السطح.
            """
        }
    },
    
    "causes_principales": {
        "keywords": {
            "fr": ["causes", "origines", "pourquoi", "provoque", "cause tsunami", "origine tsunami"],
            "en": ["causes", "origins", "why", "cause", "tsunami causes", "tsunami origins"],
            "ar": ["أسباب", "مصادر", "لماذا", "يتسبب", "أسباب تسونامي", "مصادر تسونامي"]
        },
        "responses": {
            "fr": """
**📌 CAUSES PRINCIPALES DES TSUNAMIS**

**1. SÉISMES SOUS-MARINS (90% des cas)**
- **Magnitude minimale** : > 6.5 sur l'échelle de Richter
- **Type de faille** : Mouvement vertical essentiellement
- **Exemple** : Japon 2011 (magnitude 9.0), Sumatra 2004 (9.1)

**2. GLISSEMENTS DE TERRAIN SOUS-MARINS (7%)**
- **Volume** : Peut atteindre des kilomètres cubes
- **Localisation** : Pentes continentales, volcans sous-marins
- **Exemple** : Papouasie-Nouvelle-Guinée 1998

**3. ÉRUPTIONS VOLCANIQUES (2%)**
- **Mécanisme** : Effondrement du volcan, entrée de matériaux
- **Exemple** : Krakatoa 1883 (vagues de 40m)

**4. IMPACTS DE MÉTÉORITES (1%)**
- **Rareté** : Événements exceptionnels
- **Énergie** : Extrêmement destructrice

**5. AUTRES CAUSES** : Explosions nucléaires sous-marines, effondrements glaciaires
            """,
            "en": """
**📌 MAIN TSUNAMI CAUSES**

**1. UNDERSEA EARTHQUAKES (90% of cases)**
- **Minimum magnitude**: > 6.5 on Richter scale
- **Fault type**: Primarily vertical movement
- **Example**: Japan 2011 (magnitude 9.0), Sumatra 2004 (9.1)

**2. SUBMARINE LANDSLIDES (7%)**
- **Volume**: Can reach cubic kilometers
- **Location**: Continental slopes, underwater volcanoes
- **Example**: Papua New Guinea 1998

**3. VOLCANIC ERUPTIONS (2%)**
- **Mechanism**: Volcano collapse, material entry
- **Example**: Krakatoa 1883 (40m waves)

**4. METEORITE IMPACTS (1%)**
- **Rarity**: Exceptional events
- **Energy**: Extremely destructive

**5. OTHER CAUSES**: Underwater nuclear explosions, glacial collapses
            """,
            "ar": """
**📌 الأسباب الرئيسية للتسونامي**

**1. الزلازل تحت البحر (90٪ من الحالات)**
- **الحد الأدنى للقوة**: > 6.5 على مقياس ريختر
- **نوع الصدع**: حركة رأسية primarily
- **مثال**: اليابان 2011 (قوة 9.0)، سومطرة 2004 (9.1)

**2. الانهيارات الأرضية تحت البحر (7٪)**
- **الحجم**: يمكن أن يصل إلى كيلومترات مكعبة
- **الموقع**: المنحدرات القارية، البراكين تحت الماء
- **مثال**: بابوا غينيا الجديدة 1998

**3. الثورات البركانية (2٪)**
- **الآلية**: انهيار البركان، دخول المواد
- **مثال**: كراكاتوا 1883 (أمواج 40م)

**4. اصطدام النيازك (1٪)**
- **الندرة**: أحداث استثنائية
- **الطاقة**: مدمرة للغاية

**5. أسباب أخرى**: انفجارات نووية تحت الماء، انهيارات جليدية
            """
        }
    },
    
    "seisme_tsunami": {
        "keywords": {
            "fr": ["séisme", "tremblement de terre", "comment séisme", "mécanisme séisme", "séisme provoque"],
            "en": ["earthquake", "how earthquake", "mechanism earthquake", "earthquake causes"],
            "ar": ["زلزال", "كيف زلزال", "آلية زلزال", "زلزال يتسبب"]
        },
        "responses": {
            "fr": """
**🔬 COMMENT UN SÉISME PROVOQUE UN TSUNAMI**

**Processus en 4 étapes :**

**1. RUPTURE SOUS-MARINE**
- Faille tectonique se rompt sous l'océan
- Déplacement vertical du plancher océanique (jusqu'à 10m)
- Temps : Quelques secondes à minutes

**2. DÉPLACEMENT D'EAU**
- La colonne d'eau est poussée vers le haut ou tirée vers le bas
- Création d'une "bosse" d'eau à la surface
- Énergie transmise à toute la colonne d'eau

**3. PROPAGATION DES ONDES**
- Ondes se propagent à 800 km/h en eau profonde
- Longue distance avec peu de perte d'énergie
- Amplification près des côtes

**4. DÉFERLEMENT CÔTIER**
- Ralentissement en eau peu profonde
- Amplitude des vagues multipliée par 10-30
- Inondation des terres

**Conditions nécessaires :**
- Magnitude > 6.5
- Faille à mouvement vertical
- Profondeur < 50 km
            """,
            "en": """
**🔬 HOW AN EARTHQUAKE CAUSES A TSUNAMI**

**4-step process:**

**1. UNDERSEA RUPTURE**
- Tectonic fault breaks under ocean
- Vertical displacement of ocean floor (up to 10m)
- Time: Few seconds to minutes

**2. WATER DISPLACEMENT**
- Water column pushed upward or pulled downward
- Creation of water "bulge" at surface
- Energy transmitted to entire water column

**3. WAVE PROPAGATION**
- Waves propagate at 800 km/h in deep water
- Long distance with little energy loss
- Amplification near coasts

**4. COASTAL BREAKING**
- Slowing in shallow water
- Wave amplitude multiplied by 10-30
- Land flooding

**Required conditions:**
- Magnitude > 6.5
- Vertical movement fault
- Depth < 50 km
            """,
            "ar": """
**🔬 كيف يتسبب الزلزال في تسونامي**

**عملية من 4 خطوات:**

**1. تمزق تحت البحر**
- انكسار الصدع التكتوني تحت المحيط
- الانزياح الرأسي لقاع المحيط (حتى 10م)
- الوقت: بضع ثوان إلى دقائق

**2. إزاحة الماء**
- دفع عمود الماء لأعلى أو سحبه لأسفل
- تكوين "انتفاخ" مائي على السطح
- نقل الطاقة إلى عمود الماء بالكامل

**3. انتشار الموج**
- انتشار الأمواج بسرعة 800 كم/ساعة في المياه العميقة
- مسافة طويلة مع فقدان طاقة قليل
- تضخيم بالقرب من السواحل

**4. انكسار ساحلي**
- التباطؤ في المياه الضحلة
- تضخيم سعة الموجة 10-30 مرة
- فيضان اليابسة

**الشروط المطلوبة:**
- قوة > 6.5
- صدع بحركة رأسية
- عمق < 50 كم
            """
        }
    },
    
    "volcan_glissement_tsunami": {
        "keywords": {
            "fr": ["volcan", "volcanique", "glissement", "éruption", "volcan tsunami", "glissement terrain"],
            "en": ["volcano", "volcanic", "landslide", "eruption", "volcano tsunami", "landslide tsunami"],
            "ar": ["بركان", "بركاني", "انهيار", "ثوران", "بركان تسونامي", "انهيار أرضي"]
        },
        "responses": {
            "fr": """
**🌋 TSUNAMIS VOLCANIQUES ET PAR GLISSEMENTS**

**TSUNAMIS VOLCANIQUES :**

**Mécanismes :**
1. **Effondrement du volcan** - Flancs qui s'effondrent dans la mer
2. **Pyroclastiques** - Flux de matériaux entrant dans l'eau
3. **Explosions sous-marines** - Vapeur et gaz sous pression

**Exemples célèbres :**
- **Krakatoa 1883** : Vagues de 40m, 36,000 morts
- **Santorin 1600 av.J-C** : Possible fin de la civilisation minoenne

**TSUNAMIS PAR GLISSEMENTS :**

**Types de glissements :**
- **Sous-marins** : Effondrement pentes continentales
- **Aériens** : Roches/glaciers tombant dans fjords/lacs

**Caractéristiques :**
- Plus localisés mais très destructeurs localement
- Peuvent survenir sans séisme préalable
- Difficiles à prévoir

**Exemple :** Baie Lituya 1958 - Vague de 524m (record mondial)
            """,
            "en": """
**🌋 VOLCANIC AND LANDSLIDE TSUNAMIS**

**VOLCANIC TSUNAMIS:**

**Mechanisms:**
1. **Volcano collapse** - Flanks collapsing into sea
2. **Pyroclastics** - Material flows entering water
3. **Underwater explosions** - Steam and pressurized gas

**Famous examples:**
- **Krakatoa 1883**: 40m waves, 36,000 deaths
- **Santorini 1600 BC**: Possible end of Minoan civilization

**LANDSLIDE TSUNAMIS:**

**Landslide types:**
- **Submarine**: Continental slope collapses
- **Aerial**: Rocks/glaciers falling into fjords/lakes

**Characteristics:**
- More localized but very destructive locally
- Can occur without prior earthquake
- Difficult to predict

**Example:** Lituya Bay 1958 - 524m wave (world record)
            """,
            "ar": """
**🌋 تسونامي البراكين والانهيارات**

**تسونامي البراكين:**

**الآليات:**
1. **انهيار البركان** - انهيار الأجنبة في البحر
2. **المواد البركانية** - تدفق المواد إلى الماء
3. **انفجارات تحت الماء** - البخار والغاز المضغوط

**أمثلة مشهورة:**
- **كراكاتوا 1883**: أمواج 40م، 36,000 وفاة
- **سانتوريني 1600 ق.م**: نهاية محتملة للحضارة المينوية

**تسونامي الانهيارات:**

**أنواع الانهيارات:**
- **تحت البحر**: انهيار المنحدرات القارية
- **جوي**: صخور/أنهار جليدية تسقط في المضايق/البحيرات

**الخصائص:**
- أكثر تمركزًا ولكن مدمرة جدًا محليًا
- يمكن أن تحدث بدون زلزال مسبق
- صعبة التنبؤ

**مثال:** خليج ليتويا 1958 - موجة 524م (رقم قياسي عالمي)
            """
        }
    },
    
    "signes_precurseurs": {
        "keywords": {
            "fr": ["signes", "précurseurs", "alerte", "avant tsunami", "signes avant", "reconnaître"],
            "en": ["signs", "warning", "alert", "before tsunami", "warning signs", "recognize"],
            "ar": ["علامات", "إنذار", "قبل تسونامي", "علامات إنذار", "يتعرف"]
        },
        "responses": {
            "fr": """
**⚠️ SIGNES PRÉCURSEURS D'UN TSUNAMI**

**SIGNES NATURELS (À CONNAÎTRE ABSOLUMENT) :**

**1. SÉISME FORT ET LONG**
- Durée > 20 secondes
- Impossible de rester debout
- Secousses violentes

**2. RETRAIT SOUDAIN DE LA MER**
- Mer qui se retire anormalement loin
- Fond marin visible sur des centaines de mètres
- **ATTENTION** : Ce n'est pas le moment de prendre des photos !

**3. BRUIT ANORMAL**
- Bruit de locomotive ou d'avion à réaction
- Grondement sourd venant de l'océan

**4. COMPORTEMENT ANIMAL**
- Animaux qui fuient vers les hauteurs
- Oiseaux qui s'envolent en masse

**SIGNES OFFICIELS :**
- Sirènes d'alerte tsunami
- Messages d'urgence sur téléphone
- Alertes médias et radio

**RÈGLE D'OR :** En cas de séisme côtier, évacuez immédiatement sans attendre les signes visuels !
            """,
            "en": """
**⚠️ TSUNAMI WARNING SIGNS**

**NATURAL SIGNS (MUST KNOW):**

**1. STRONG, LONG EARTHQUAKE**
- Duration > 20 seconds
- Cannot stand upright
- Violent shaking

**2. SUDDEN SEA RETREAT**
- Sea retreating abnormally far
- Seabed visible for hundreds of meters
- **WARNING**: Not the time for photos!

**3. ABNORMAL NOISE**
- Locomotive or jet engine noise
- Deep roar from ocean

**4. ANIMAL BEHAVIOR**
- Animals fleeing to high ground
- Birds flying away en masse

**OFFICIAL SIGNS:**
- Tsunami warning sirens
- Emergency phone messages
- Media and radio alerts

**GOLDEN RULE:** During coastal earthquake, evacuate immediately without waiting for visual signs!
            """,
            "ar": """
**⚠️ علامات إنذار التسونامي**

**العلامات الطبيعية (يجب معرفتها):**

**1. زلزال قوي وطويل**
- المدة > 20 ثانية
- عدم القدرة على الوقوف
- اهتزازات عنيفة

**2. انسحاب مفاجئ للبحر**
- تراجع البحر بشكل غير طبيعي
- قاع البحر مرئي لمئات الأمتار
- **تحذير**: ليس وقتًا لالتقاط الصور!

**3. ضجيج غير طبيعي**
- ضجيج مثل القطار أو المحرك النفاث
- هدير عميق قادم من المحيط

**4. سلوك الحيوان**
- حيوانات تهرب إلى المرتفعات
- طيور تطير بعيدًا بأعداد كبيرة

**العلامات الرسمية:**
- صفارات إنذار التسونامي
- رسائل طوارئ على الهاتف
- تنبيهات الإعلام والراديو

**القاعدة الذهبية:** أثناء الزلزال الساحلي، اخل فورًا دون انتظار العلامات المرئية!
            """
        }
    },
    
    # ========== CONSÉQUENCES ==========
    "consequences_humaines": {
        "keywords": {
            "fr": ["conséquences humaines", "victimes", "morts", "décès", "impact humain"],
            "en": ["human consequences", "victims", "deaths", "human impact"],
            "ar": ["عواقب بشرية", "ضحايا", "وفيات", "تأثير بشري"]
        },
        "responses": {
            "fr": """
**😢 CONSÉQUENCES HUMAINES DES TSUNAMIS**

**IMPACTS IMMÉDIATS :**

**1. MORTS ET BLESSÉS**
- **Noyade** (cause principale de décès)
- **Traumatismes physiques** (fractures, blessures)
- **Hypothermie** en eau froide

**2. DÉPLACEMENTS DE POPULATION**
- Maisons détruites
- Infrastructures endommagées
- Réfugiés environnementaux

**STATISTIQUES :**
- **Tsunami 2004** : 230,000-280,000 morts
- **Japon 2011** : 18,000 morts confirmés
- **Moyenne historique** : Variable selon l'événement

**FACTEURS INFLUENÇANT LA MORTALITÉ :**
- Densité de population côtière
- Heure de la journée (nuit = plus dangereux)
- Systèmes d'alerte en place
- Éducation de la population
            """,
            "en": """
**😢 HUMAN CONSEQUENCES OF TSUNAMIS**

**IMMEDIATE IMPACTS:**

**1. DEATHS AND INJURIES**
- **Drowning** (main cause of death)
- **Physical trauma** (fractures, injuries)
- **Hypothermia** in cold water

**2. POPULATION DISPLACEMENT**
- Homes destroyed
- Damaged infrastructure
- Environmental refugees

**STATISTICS:**
- **2004 tsunami**: 230,000-280,000 deaths
- **Japan 2011**: 18,000 confirmed deaths
- **Historical average**: Varies by event

**FACTORS INFLUENCING MORTALITY:**
- Coastal population density
- Time of day (night = more dangerous)
- Warning systems in place
- Population education
            """,
            "ar": """
**😢 العواقب البشرية للتسونامي**

**الآثار الفورية:**

**1. الوفيات والإصابات**
- **الغرق** (السبب الرئيسي للوفاة)
- **الصدمات الجسدية** (كسور، إصابات)
- **انخفاض حرارة الجسم** في الماء البارد

**2. نزوح السكان**
- تدمير المنازل
- تلف البنية التحتية
- لاجئون بيئيون

**الإحصائيات:**
- **تسونامي 2004**: 230,000-280,000 وفاة
- **اليابان 2011**: 18,000 وفاة مؤكدة
- **المتوسط التاريخي**: يختلف حسب الحدث

**العوامل المؤثرة على الوفيات:**
- كثافة السكان الساحليين
- وقت اليوم (الليل = أكثر خطورة)
- أنظمة الإنذار الموجودة
- تثقيف السكان
            """
        }
    },
    
    "impacts_economiques": {
        "keywords": {
            "fr": ["impacts économiques", "économique", "économie", "coût", "dégâts économiques", "pertes financières"],
            "en": ["economic impacts", "economic", "economy", "cost", "economic damage", "financial losses"],
            "ar": ["الآثار الاقتصادية", "اقتصادي", "اقتصاد", "تكلفة", "الضرر الاقتصادي", "الخسائر المالية"]
        },
        "responses": {
            "fr": """
**💰 IMPACTS ÉCONOMIQUES DES TSUNAMIS**

**DÉGÂTS DIRECTS :**

**1. INFRASTRUCTURES DÉTRUITES**
- **Ports et installations portuaires** : Interruption du commerce maritime
- **Routes et ponts** : Isolement des régions affectées
- **Réseaux électriques** : Pannes généralisées
- **Usines et zones industrielles** : Arrêt de production

**2. SECTEUR TOURISTIQUE**
- **Hôtels et stations balnéaires** : Destruction complète
- **Plages et attractions** : Dégradation pour des années
- **Perte de revenus touristiques** : Effet à long terme

**3. AGRICULTURE ET PÊCHE**
- **Salinisation des terres** : Rendements réduits pour des années
- **Flottes de pêche** : Bateaux et équipements détruits
- **Aquaculture** : Fermes maritimes anéanties

**COÛTS ÉCONOMIQUES :**

**Exemples concrets :**
- **Japon 2011** : 235 milliards USD de dégâts
- **Sumatra 2004** : 15 milliards USD dans 14 pays
- **Reconstruction** : Prend 5-10 ans en moyenne

**EFFETS À LONG TERME :**
- **Dette nationale** augmentation pour financer la reconstruction
- **Croissance économique** ralentie pendant des années
- **Assurances** : Augmentation des primes dans les zones à risque
- **Relocalisation** des activités économiques vers l'intérieur des terres
            """,
            "en": """
**💰 ECONOMIC IMPACTS OF TSUNAMIS**

**DIRECT DAMAGES:**

**1. DESTROYED INFRASTRUCTURE**
- **Ports and harbor facilities**: Disruption of maritime trade
- **Roads and bridges**: Isolation of affected regions
- **Power networks**: Widespread outages
- **Factories and industrial zones**: Production stoppage

**2. TOURISM SECTOR**
- **Hotels and resorts**: Complete destruction
- **Beaches and attractions**: Degradation for years
- **Loss of tourism revenue**: Long-term effect

**3. AGRICULTURE AND FISHING**
- **Land salinization**: Reduced yields for years
- **Fishing fleets**: Boats and equipment destroyed
- **Aquaculture**: Marine farms wiped out

**ECONOMIC COSTS:**

**Concrete examples:**
- **Japan 2011**: 235 billion USD in damages
- **Sumatra 2004**: 15 billion USD across 14 countries
- **Reconstruction**: Takes 5-10 years on average

**LONG-TERM EFFECTS:**
- **National debt** increase to finance reconstruction
- **Economic growth** slowed for years
- **Insurance**: Premium increases in risk zones
- **Relocation** of economic activities inland
            """,
            "ar": """
**💰 الآثار الاقتصادية للتسونامي**

**الضرر المباشر:**

**1. البنية التحتية المدمرة**
- **الموانئ والمرافئ**: تعطيل التجارة البحرية
- **الطرق والجسور**: عزل المناطق المتضررة
- **شبكات الكهرباء**: انقطاعات واسعة النطاق
- **المصانع والمناطق الصناعية**: توقف الإنتاج

**2. قطاع السياحة**
- **الفنادق والمنتجعات**: تدمير كامل
- **الشواطئ والمعالم السياحية**: تدهور لسنوات
- **فقدان إيرادات السياحة**: تأثير طويل الأمد

**3. الزراعة والصيد**
- **تملح الأراضي**: انخفاض الغلات لسنوات
- **أساطيل الصيد**: تدمير القوارب والمعدات
- **تربية الأحياء المائية**: تدمير المزارع البحرية

**التكاليف الاقتصادية:**

**أمثلة ملموسة:**
- **اليابان 2011**: 235 مليار دولار أضرار
- **سومطرة 2004**: 15 مليار دولار عبر 14 دولة
- **إعادة الإعمار**: تستغرق 5-10 سنوات في المتوسط

**الآثار طويلة الأجل:**
- **زيادة الدَّين الوطني** لتمويل إعادة الإعمار
- **تباطؤ النمو الاقتصادي** لسنوات
- **التأمين**: زيادة الأقساط في مناطق الخطر
- **إعادة توطين** الأنشطة الاقتصادية في الداخل
            """
        }
    },
    
    "impacts_environnementaux": {
        "keywords": {
            "fr": ["environnement", "écologie", "biodiversité", "impact environnemental", "nature"],
            "en": ["environment", "ecology", "biodiversity", "environmental impact", "nature"],
            "ar": ["بيئة", "إيكولوجيا", "تنوع حيوي", "تأثير بيئي", "طبيعة"]
        },
        "responses": {
            "fr": """
**🌿 IMPACTS ENVIRONNEMENTAUX DES TSUNAMIS**

**DÉGÂTS ÉCOSYSTÉMIQUES :**

**1. ÉCOSYSTÈMES MARINS**
- **Récifs coralliens** : Brisés et ensevelis
- **Herbiers marins** : Arrachés et détruits
- **Habitats côtiers** : Modifiés radicalement

**2. ÉCOSYSTÈMES TERRESTRES**
- **Forêts côtières** : Dévastées par le sel et la force
- **Zones humides** : Envasement et salinisation
- **Sols agricoles** : Stérilisés par le sel marin

**3. FAUNE ET FLORE**
- **Espèces marines** : Mortalité massive
- **Oiseaux côtiers** : Perte d'habitats de nidification
- **Espèces invasives** : Introduction par les débris

**POLLUTION :**
- **Déchets et débris** : Millions de tonnes dispersées
- **Produits chimiques** : Fuites d'usines et réservoirs
- **Eaux contaminées** : Problèmes sanitaires

**RÉSILIENCE NATURELLE :**
- Certains écosystèmes se reconstituent en 5-10 ans
- Les récifs coralliens peuvent mettre 20-50 ans
- Adaptation des espèces survivantes
            """,
            "en": """
**🌿 ENVIRONMENTAL IMPACTS OF TSUNAMIS**

**ECOSYSTEM DAMAGES:**

**1. MARINE ECOSYSTEMS**
- **Coral reefs**: Broken and buried
- **Seagrass beds**: Uprooted and destroyed
- **Coastal habitats**: Radically modified

**2. TERRESTRIAL ECOSYSTEMS**
- **Coastal forests**: Devastated by salt and force
- **Wetlands**: Siltation and salinization
- **Agricultural soils**: Sterilized by sea salt

**3. FAUNA AND FLORA**
- **Marine species**: Massive mortality
- **Coastal birds**: Loss of nesting habitats
- **Invasive species**: Introduction through debris

**POLLUTION:**
- **Waste and debris**: Millions of tons dispersed
- **Chemicals**: Leaks from factories and tanks
- **Contaminated waters**: Health problems

**NATURAL RESILIENCE:**
- Some ecosystems recover in 5-10 years
- Coral reefs can take 20-50 years
- Adaptation of surviving species
            """,
            "ar": """
**🌿 الآثار البيئية للتسونامي**

**أضرار النظم البيئية:**

**1. النظم البيئية البحرية**
- **الشعاب المرجانية**: مكسورة ومدفونة
- **مروج الأعشاب البحرية**: اقتلعت ودمرت
- **الموائل الساحلية**: تعدلت بشكل جذري

**2. النظم البيئية الأرضية**
- **الغابات الساحلية**: دمرت بالملح والقوة
- **الأراضي الرطبة**: الترسيب والتملح
- **التربة الزراعية**: تعقيمها بملح البحر

**3. الحيوانات والنباتات**
- **الأنواع البحرية**: نفوق جماعي
- **الطيور الساحلية**: فقدان موائل التعشيش
- **الأنواع الغازية**: إدخال عبر الحطام

**التلوث:**
- **النفايات والحطام**: ملايين الأطنان منتشرة
- **المواد الكيميائية**: تسرب من المصانع والخزانات
- **المياه الملوثة**: مشاكل صحية

**القدرة الطبيعية على التعافي:**
- بعض النظم البيئية تتعافى في 5-10 سنوات
- الشعاب المرجانية قد تستغرق 20-50 سنة
- تكيف الأنواع الناجية
            """
        }
    },
    
    "exemples_degats_importants": {
        "keywords": {
            "fr": ["exemples", "tsunamis importants", "dégâts importants", "catastrophes", "historique"],
            "en": ["examples", "major tsunamis", "significant damage", "disasters", "historical"],
            "ar": ["أمثلة", "تسونامي كبيرة", "أضرار كبيرة", "كوارث", "تاريخي"]
        },
        "responses": {
            "fr": """
**📊 TSUNAMIS AYANT CAUSÉ DES DÉGÂTS IMPORTANTS**

**1. TSUNAMI DE L'OCÉAN INDIEN 2004**
- **Cause** : Séisme magnitude 9.1 au large de Sumatra
- **Pays touchés** : 14 pays dont Indonésie, Thaïlande, Sri Lanka
- **Bilan** : 230,000-280,000 morts
- **Dégâts** : 15 milliards USD

**2. TSUNAMI DU JAPON 2011**
- **Cause** : Séisme magnitude 9.0 + accident nucléaire Fukushima
- **Hauteur vagues** : Jusqu'à 40m
- **Bilan** : 18,000 morts, 2,500 disparus
- **Dégâts** : 235 milliards USD

**3. TSUNAMI DE LISBONNE 1755**
- **Cause** : Séisme magnitude 8.5-9.0
- **Pays touchés** : Portugal, Espagne, Maroc
- **Bilan** : 50,000-100,000 morts
- **Particularité** : Premier tsunami étudié scientifiquement

**4. TSUNAMI DU KRAKATOA 1883**
- **Cause** : Éruption volcanique
- **Hauteur vagues** : 40m
- **Bilan** : 36,000 morts
- **Portée** : Vagues ressenties jusqu'en Angleterre

**5. TSUNAMI DU CHILI 1960**
- **Cause** : Plus grand séisme enregistré (magnitude 9.5)
- **Pays touchés** : Chili, Hawaii, Japon, Philippines
- **Bilan** : 6,000 morts
- **Portée** : Vagues traversent tout le Pacifique
            """,
            "en": """
**📊 TSUNAMIS CAUSING SIGNIFICANT DAMAGE**

**1. 2004 INDIAN OCEAN TSUNAMI**
- **Cause**: Magnitude 9.1 earthquake off Sumatra
- **Affected countries**: 14 countries including Indonesia, Thailand, Sri Lanka
- **Toll**: 230,000-280,000 deaths
- **Damage**: 15 billion USD

**2. 2011 JAPAN TSUNAMI**
- **Cause**: Magnitude 9.0 earthquake + Fukushima nuclear accident
- **Wave height**: Up to 40m
- **Toll**: 18,000 deaths, 2,500 missing
- **Damage**: 235 billion USD

**3. 1755 LISBON TSUNAMI**
- **Cause**: Magnitude 8.5-9.0 earthquake
- **Affected countries**: Portugal, Spain, Morocco
- **Toll**: 50,000-100,000 deaths
- **Particularity**: First scientifically studied tsunami

**4. 1883 KRAKATOA TSUNAMI**
- **Cause**: Volcanic eruption
- **Wave height**: 40m
- **Toll**: 36,000 deaths
- **Range**: Waves felt as far as England

**5. 1960 CHILE TSUNAMI**
- **Cause**: Largest recorded earthquake (magnitude 9.5)
- **Affected countries**: Chile, Hawaii, Japan, Philippines
- **Toll**: 6,000 deaths
- **Range**: Waves crossed entire Pacific
            """,
            "ar": """
**📊 تسونامي تسببت في أضرار كبيرة**

**1. تسونامي المحيط الهندي 2004**
- **السبب**: زلزال قوة 9.1 قبالة سومطرة
- **الدول المتضررة**: 14 دولة بما فيها إندونيسيا، تايلاند، سريلانكا
- **الخسائر**: 230,000-280,000 وفاة
- **الأضرار**: 15 مليار دولار

**2. تسونامي اليابان 2011**
- **السبب**: زلزال قوة 9.0 + حادث فوكوشيما النووي
- **ارتفاع الأمواج**: حتى 40م
- **الخسائر**: 18,000 وفاة، 2,500 مفقود
- **الأضرار**: 235 مليار دولار

**3. تسونامي لشبونة 1755**
- **السبب**: زلزال قوة 8.5-9.0
- **الدول المتضررة**: البرتغال، إسبانيا، المغرب
- **الخسائر**: 50,000-100,000 وفاة
- **الخصوصية**: أول تسونامي يدرس علميًا

**4. تسونامي كراكاتوا 1883**
- **السبب**: ثوران بركاني
- **ارتفاع الأمواج**: 40م
- **الخسائر**: 36,000 وفاة
- **المدى**: أمواج شعر بها حتى إنجلترا

**5. تسونامي تشيلي 1960**
- **السبب**: أكبر زلزال مسجل (قوة 9.5)
- **الدول المتضررة**: تشيلي، هاواي، اليابان، الفلبين
- **الخسائر**: 6,000 وفاة
- **المدى**: أمواج عبرت المحيط الهادئ بالكامل
            """
        }
    },
    
    "effets_long_terme_populations": {
        "keywords": {
            "fr": ["effets long terme", "long terme", "populations touchées", "conséquences durables", "après tsunami"],
            "en": ["long term effects", "long term", "affected populations", "lasting consequences", "after tsunami"],
            "ar": ["آثار طويلة الأجل", "طويل الأجل", "المتضررين", "عواقب دائمة", "بعد تسونامي"]
        },
        "responses": {
            "fr": """
**⏳ EFFETS À LONG TERME SUR LES POPULATIONS TOUCHÉES**

**SANTÉ MENTALE :**
- **Syndrome de stress post-traumatique** : 30-40% des survivants
- **Dépression et anxiété** : Augmentation significative
- **Problèmes de sommeil** : Cauchemars récurrents
- **Deuil compliqué** : Perte de famille entière

**SANTÉ PHYSIQUE :**
- **Maladies chroniques** : Aggravation des conditions existantes
- **Problèmes respiratoires** : Poussières et moisissures
- **Maladies infectieuses** : Eau contaminée, surpopulation

**SOCIAL ET ÉCONOMIQUE :**
- **Déplacement permanent** : Relocalisation des communautés
- **Chômage prolongé** : Destruction des moyens de subsistance
- **Pauvreté accrue** : Perte d'épargne et de biens
- **Problèmes familiaux** : Séparations, divorces

**CULTUREL ET COMMUNAUTAIRE :**
- **Perte de traditions** : Disparition d'anciens et de savoirs
- **Changements démographiques** : Jeunesse qui quitte la région
- **Réseaux sociaux brisés** : Communautés dispersées

**RÉSILIENCE ET RECONSTRUCTION :**
- **Reconstruction physique** : 5-10 ans minimum
- **Rétablissement économique** : 10-20 ans
- **Guérison psychologique** : Générations entières
            """,
            "en": """
**⏳ LONG-TERM EFFECTS ON AFFECTED POPULATIONS**

**MENTAL HEALTH:**
- **Post-traumatic stress disorder**: 30-40% of survivors
- **Depression and anxiety**: Significant increase
- **Sleep problems**: Recurrent nightmares
- **Complicated grief**: Loss of entire family

**PHYSICAL HEALTH:**
- **Chronic diseases**: Worsening of existing conditions
- **Respiratory problems**: Dust and mold
- **Infectious diseases**: Contaminated water, overcrowding

**SOCIAL AND ECONOMIC:**
- **Permanent displacement**: Relocation of communities
- **Prolonged unemployment**: Destruction of livelihoods
- **Increased poverty**: Loss of savings and assets
- **Family problems**: Separations, divorces

**CULTURAL AND COMMUNITY:**
- **Loss of traditions**: Disappearance of elders and knowledge
- **Demographic changes**: Youth leaving the region
- **Broken social networks**: Dispersed communities

**RESILIENCE AND RECONSTRUCTION:**
- **Physical reconstruction**: 5-10 years minimum
- **Economic recovery**: 10-20 years
- **Psychological healing**: Entire generations
            """,
            "ar": """
**⏳ الآثار طويلة الأجل على السكان المتضررين**

**الصحة النفسية:**
- **اضطراب ما بعد الصدمة**: 30-40٪ من الناجين
- **الاكتئاب والقلق**: زيادة كبيرة
- **مشاكل النوم**: كوابيس متكررة
- **الحزن المعقد**: فقدان العائلة بأكملها

**الصحة البدنية:**
- **الأمراض المزمنة**: تفاقم الحالات الموجودة
- **مشاكل الجهاز التنفسي**: الغبار والعفن
- **الأمراض المعدية**: مياه ملوثة، اكتظاظ

**الاجتماعي والاقتصادي:**
- **النزوح الدائم**: إعادة توطين المجتمعات
- **البطالة المطولة**: تدمير سبل العيش
- **زيادة الفقر**: فقدان المدخرات والممتلكات
- **مشاكل عائلية**: انفصالات، طلاق

**الثقافي والمجتمعي:**
- **فقدان التقاليد**: اختفاء المسنين والمعارف
- **التغيرات الديموغرافية**: الشباب يغادرون المنطقة
- **انكسار الشبكات الاجتماعية**: مجتمعات مشتتة

**القدرة على التعافي وإعادة الإعمار:**
- **إعادة الإعمار المادي**: 5-10 سنوات كحد أدنى
- **الانتعاش الاقتصادي**: 10-20 سنة
- **الشفاء النفسي**: أجيال كاملة
            """
        }
    },
    
    "mortalite_moyenne_tsunami": {
        "keywords": {
            "fr": ["mortalité", "moyenne", "morts", "décès", "statistiques", "combien meurent"],
            "en": ["mortality", "average", "deaths", "statistics", "how many die"],
            "ar": ["وفيات", "متوسط", "قتلى", "إحصائيات", "كم يموت"]
        },
        "responses": {
            "fr": """
**📈 MORTALITÉ MOYENNE LORS DES TSUNAMIS**

**STATISTIQUES GLOBALES :**

**Données historiques :**
- **Moyenne générale** : Très variable selon l'événement
- **Tsunamis majeurs** : 1,000 à 300,000 morts
- **Tsunamis mineurs** : Moins de 100 morts

**Facteurs influençant la mortalité :**

**1. DENSITÉ DE POPULATION**
- Zones côtières densément peuplées = plus de victimes
- Exemple : Sumatra 2004 (populations côtières denses)

**2. SYSTÈMES D'ALERTE**
- Avec système d'alerte : Réduction de 50-80% de la mortalité
- Sans système : Multiplication des victimes

**3. HEURE DE LA JOURNÉE**
- Nuit : +40% de mortalité (difficulté d'évacuation)
- Jour : Meilleure visibilité des signes

**4. TOPOGRAPHIE CÔTIÈRE**
- Plates et basses : Plus dangereuses
- Côtes élevées : Moins de risques

**EXEMPLES CONCRETS :**
- **2004 Océan Indien** : 230,000-280,000 (peu ou pas d'alerte)
- **2011 Japon** : 18,000 (système d'alerte efficace mais vague exceptionnelle)
- **1960 Chili** : 6,000 (alerte limitée)

**TENDANCE :** La mortalité diminue avec l'amélioration des systèmes d'alerte et de l'éducation.
            """,
            "en": """
**📈 AVERAGE MORTALITY IN TSUNAMIS**

**GLOBAL STATISTICS:**

**Historical data:**
- **General average**: Highly variable by event
- **Major tsunamis**: 1,000 to 300,000 deaths
- **Minor tsunamis**: Less than 100 deaths

**Factors influencing mortality:**

**1. POPULATION DENSITY**
- Densely populated coastal areas = more victims
- Example: Sumatra 2004 (dense coastal populations)

**2. WARNING SYSTEMS**
- With warning system: 50-80% mortality reduction
- Without system: Multiplication of victims

**3. TIME OF DAY**
- Night: +40% mortality (evacuation difficulty)
- Day: Better visibility of signs

**4. COASTAL TOPOGRAPHY**
- Flat and low: More dangerous
- High coasts: Less risk

**CONCRETE EXAMPLES:**
- **2004 Indian Ocean**: 230,000-280,000 (little or no warning)
- **2011 Japan**: 18,000 (effective warning system but exceptional wave)
- **1960 Chile**: 6,000 (limited warning)

**TREND:** Mortality decreases with improvement of warning systems and education.
            """,
            "ar": """
**📈 متوسط الوفيات في تسونامي**

**الإحصائيات العالمية:**

**البيانات التاريخية:**
- **المتوسط العام**: متغير للغاية حسب الحدث
- **تسونامي كبيرة**: 1,000 إلى 300,000 وفاة
- **تسونامي صغيرة**: أقل من 100 وفاة

**العوامل المؤثرة على الوفيات:**

**1. الكثافة السكانية**
- المناطق الساحلية المكتظة = المزيد من الضحايا
- مثال: سومطرة 2004 (كثافات ساحلية عالية)

**2. أنظمة الإنذار**
- مع نظام إنذار: تخفيض الوفيات 50-80٪
- بدون نظام: تضاعف الضحايا

**3. وقت اليوم**
- الليل: +40٪ وفيات (صعوبة الإخلاء)
- النهار: رؤية أفضل للعلامات

**4. التضاريس الساحلية**
- منخفضة ومسطحة: أكثر خطورة
- سواحل مرتفعة: أقل خطرًا

**أمثلة ملموسة:**
- **2004 المحيط الهندي**: 230,000-280,000 (قليل أو لا إنذار)
- **2011 اليابان**: 18,000 (نظام إنذار فعال لكن موجة استثنائية)
- **1960 تشيلي**: 6,000 (إنذار محدود)

**الاتجاه:** تنخفض الوفيات مع تحسن أنظمة الإنذار والتثقيف.
            """
        }
    },
    
    # ========== EXEMPLES HISTORIQUES ==========
    "tsunami_2004": {
        "keywords": {
            "fr": ["2004", "océan indien", "sumatra", "thailande", "sri lanka", "indonésie 2004"],
            "en": ["2004", "indian ocean", "sumatra", "thailand", "sri lanka", "indonesia 2004"],
            "ar": ["2004", "المحيط الهندي", "سومطرة", "تايلاند", "سريلانكا", "إندونيسيا 2004"]
        },
        "responses": {
            "fr": """
**🌊 TSUNAMI DE L'OCÉAN INDIEN 2004**

**CONTEXTE :**
- **Date** : 26 décembre 2004
- **Heure** : 7h58 heure locale
- **Épicentre** : Au large de Sumatra, Indonésie

**CARACTÉRISTIQUES :**
- **Cause** : Séisme magnitude 9.1-9.3
- **Durée** : 8-10 minutes (un des plus longs séismes)
- **Rupture** : 1,600 km de faille
- **Déplacement** : 15 mètres vertical

**IMPACT HUMAIN :**
- **Pays touchés** : 14 pays
- **Morts confirmés** : 230,000-280,000
- **Disparus** : 45,000
- **Déplacés** : 1.7 million

**DÉGÂTS ÉCONOMIQUES :**
- **Coût total** : 15 milliards USD
- **Secteur touristique** : Dévasté
- **Infrastructures** : Détruites sur des milliers de km

**RÉPONSE INTERNATIONALE :**
- **Aide humanitaire** : 14 milliards USD
- **Opérations** : Plus grande opération humanitaire de l'histoire
- **Systèmes d'alerte** : Création du système d'alerte tsunami dans l'océan Indien

**LEÇONS APPRISES :**
- Nécessité de systèmes d'alerte régionaux
- Importance de l'éducation des populations côtières
- Coordination internationale améliorée
            """,
            "en": """
**🌊 2004 INDIAN OCEAN TSUNAMI**

**CONTEXT:**
- **Date**: December 26, 2004
- **Time**: 7:58 local time
- **Epicenter**: Off the coast of Sumatra, Indonesia

**CHARACTERISTICS:**
- **Cause**: Magnitude 9.1-9.3 earthquake
- **Duration**: 8-10 minutes (one of longest earthquakes)
- **Rupture**: 1,600 km of fault
- **Displacement**: 15 meters vertical

**HUMAN IMPACT:**
- **Affected countries**: 14 countries
- **Confirmed deaths**: 230,000-280,000
- **Missing**: 45,000
- **Displaced**: 1.7 million

**ECONOMIC DAMAGE:**
- **Total cost**: 15 billion USD
- **Tourism sector**: Devastated
- **Infrastructure**: Destroyed for thousands of km

**INTERNATIONAL RESPONSE:**
- **Humanitarian aid**: 14 billion USD
- **Operations**: Largest humanitarian operation in history
- **Warning systems**: Creation of Indian Ocean tsunami warning system

**LESSONS LEARNED:**
- Need for regional warning systems
- Importance of coastal population education
- Improved international coordination
            """,
            "ar": """
**🌊 تسونامي المحيط الهندي 2004**

**السياق:**
- **التاريخ**: 26 ديسمبر 2004
- **الوقت**: 7:58 بالتوقيت المحلي
- **المركز**: قبالة سواحل سومطرة، إندونيسيا

**الخصائص:**
- **السبب**: زلزال قوة 9.1-9.3
- **المدة**: 8-10 دقائق (من أطول الزلازل)
- **التمزق**: 1,600 كم من الصدع
- **الإزاحة**: 15 متر رأسي

**التأثير البشري:**
- **الدول المتضررة**: 14 دولة
- **الوفيات المؤكدة**: 230,000-280,000
- **مفقودون**: 45,000
- **نازحون**: 1.7 مليون

**الضرر الاقتصادي:**
- **التكلفة الإجمالية**: 15 مليار دولار
- **قطاع السياحة**: مدمر
- **البنية التحتية**: دمرت لآلاف الكيلومترات

**الاستجابة الدولية:**
- **المساعدات الإنسانية**: 14 مليار دولار
- **العمليات**: أكبر عملية إنسانية في التاريخ
- **أنظمة الإنذار**: إنشاء نظام إنذار تسونامي المحيط الهندي

**الدروس المستفادة:**
- الحاجة لأنظمة إنذار إقليمية
- أهمية تثقيف السكان الساحليين
- تحسين التنسيق الدولي
            """
        }
    },
    
    "tsunami_japon_2011": {
        "keywords": {
            "fr": ["japon 2011", "fukushima", "sendai", "tsunami japon", "2011"],
            "en": ["japan 2011", "fukushima", "sendai", "japan tsunami", "2011"],
            "ar": ["اليابان 2011", "فوكوشيما", "سنداي", "تسونامي اليابان", "2011"]
        },
        "responses": {
            "fr": """
**🌊 TSUNAMI DU JAPON 2011**

**CONTEXTE :**
- **Date** : 11 mars 2011
- **Heure** : 14h46 heure locale
- **Nom** : "Grand séisme de l'Est du Japon"

**CARACTÉRISTIQUES :**
- **Séisme** : Magnitude 9.0-9.1
- **Épicentre** : 70 km à l'est de Sendai
- **Durée** : 6 minutes
- **Tsunami** : Vagues jusqu'à 40m de haut

**IMPACT IMMÉDIAT :**
- **Morts confirmés** : 18,000
- **Disparus** : 2,500
- **Blessés** : 6,000
- **Bâtiments détruits** : 130,000

**ACCIDENT NUCLÉAIRE :**
- **Centrale Fukushima Daiichi** : Fusion de 3 réacteurs
- **Évacuation** : 154,000 personnes
- **Zone d'exclusion** : 20km de rayon
- **Niveau INES** : 7 (le plus élevé)

**DÉGÂTS ÉCONOMIQUES :**
- **Coût total** : 235 milliards USD
- **Perturbations** : Chaines d'approvisionnement mondiales
- **Production** : Arrêt de nombreuses usines

**RÉPONSE ET RECONSTRUCTION :**
- **Digue** : Reconstruction de 400km de digues
- **Relocalisation** : Déplacement de communautés entières
- **Systèmes d'alerte** : Amélioration des technologies
- **Éducation** : Renforcement des exercices d'évacuation

**LEÇONS :**
- Limites des défenses côtières
- Importance de la préparation aux catast multiples
- Nécessité de plans d'évacuation rapide
            """,
            "en": """
**🌊 2011 JAPAN TSUNAMI**

**CONTEXT:**
- **Date**: March 11, 2011
- **Time**: 14:46 local time
- **Name**: "Great East Japan Earthquake"

**CHARACTERISTICS:**
- **Earthquake**: Magnitude 9.0-9.1
- **Epicenter**: 70 km east of Sendai
- **Duration**: 6 minutes
- **Tsunami**: Waves up to 40m high

**IMMEDIATE IMPACT:**
- **Confirmed deaths**: 18,000
- **Missing**: 2,500
- **Injured**: 6,000
- **Destroyed buildings**: 130,000

**NUCLEAR ACCIDENT:**
- **Fukushima Daiichi plant**: 3 reactor meltdowns
- **Evacuation**: 154,000 people
- **Exclusion zone**: 20km radius
- **INES level**: 7 (highest)

**ECONOMIC DAMAGE:**
- **Total cost**: 235 billion USD
- **Disruptions**: Global supply chains
- **Production**: Shutdown of many factories

**RESPONSE AND RECONSTRUCTION:**
- **Seawalls**: Reconstruction of 400km of seawalls
- **Relocation**: Displacement of entire communities
- **Warning systems**: Technology improvements
- **Education**: Enhanced evacuation drills

**LESSONS:**
- Limits of coastal defenses
- Importance of multi-disaster preparation
- Need for rapid evacuation plans
            """,
            "ar": """
**🌊 تسونامي اليابان 2011**

**السياق:**
- **التاريخ**: 11 مارس 2011
- **الوقت**: 14:46 بالتوقيت المحلي
- **الاسم**: "زلزال شرق اليابان الكبير"

**الخصائص:**
- **الزلزال**: قوة 9.0-9.1
- **المركز**: 70 كم شرق سنداي
- **المدة**: 6 دقائق
- **التسونامي**: أمواج حتى 40م ارتفاع

**التأثير الفوري:**
- **الوفيات المؤكدة**: 18,000
- **مفقودون**: 2,500
- **مصابون**: 6,000
- **مباني مدمرة**: 130,000

**الحادث النووي:**
- **محطة فوكوشيما داييتشي**: انصهار 3 مفاعلات
- **الإخلاء**: 154,000 شخص
- **منطقة الاستبعاد**: نصف قطر 20كم
- **مستوى INES**: 7 (الأعلى)

**الضرر الاقتصادي:**
- **التكلفة الإجمالية**: 235 مليار دولار
- **الاضطرابات**: سلاسل التوريد العالمية
- **الإنتاج**: توقف العديد من المصانع

**الاستجابة وإعادة الإعمار:**
- **السدود**: إعادة بناء 400كم من السدود
- **إعادة التوطين**: نقل مجتمعات بأكملها
- **أنظمة الإنذار**: تحسين التكنولوجيا
- **التعليم**: تعزيز تدريبات الإخلاء

**الدروس:**
- حدود الدفاعات الساحلية
- أهمية الاستعداد للكوارث المتعددة
- ضرورة خطط الإخلاء السريع
            """
        }
    },
    
    "tsunamis_meurtriers_histoire": {
        "keywords": {
            "fr": ["tsunamis meurtriers", "plus meurtriers", "histoire", "catastrophes historiques"],
            "en": ["deadliest tsunamis", "most deadly", "history", "historical disasters"],
            "ar": ["تسونامي مميتة", "الأكثر فتكًا", "تاريخ", "كوارث تاريخية"]
        },
        "responses": {
            "fr": """
**📜 TSUNAMIS LES PLUS MEURTRIERS DE L'HISTOIRE**

**CLASSEMENT HISTORIQUE :**

**1. OCÉAN INDIEN 2004** 🌊
- **Morts** : 230,000-280,000
- **Cause** : Séisme magnitude 9.1
- **Pays** : 14 nations affectées

**2. MESSINE 1908** 🇮🇹
- **Morts** : 123,000
- **Cause** : Séisme + tsunami
- **Région** : Détroit de Messine, Italie

**3. LISBONNE 1755** 🇵🇹
- **Morts** : 50,000-100,000
- **Cause** : Séisme magnitude 8.5-9.0
- **Particularité** : Jour de la Toussaint

**4. KRAKATOA 1883** 🌋
- **Morts** : 36,000
- **Cause** : Éruption volcanique
- **Vagues** : Jusqu'à 40m

**5. NANKAI 1498** 🇯🇵
- **Morts** : 31,000
- **Cause** : Séisme magnitude 8.6
- **Région** : Côte sud du Japon

**6. TOHOKU 2011** 🇯🇵
- **Morts** : 18,000
- **Cause** : Séisme magnitude 9.0
- **Particularité** : Accident nucléaire

**7. PAPOUE 1998** 🇵🇬
- **Morts** : 2,200
- **Cause** : Séisme + glissement terrain
- **Vagues** : 15m

**TENDANCES :**
- Augmentation des victimes avec la densité côtière
- Réduction récente grâce aux systèmes d'alerte
- Importance croissante de la préparation
            """,
            "en": """
**📜 DEADLIEST TSUNAMIS IN HISTORY**

**HISTORICAL RANKING:**

**1. INDIAN OCEAN 2004** 🌊
- **Deaths**: 230,000-280,000
- **Cause**: Magnitude 9.1 earthquake
- **Countries**: 14 nations affected

**2. MESSINA 1908** 🇮🇹
- **Deaths**: 123,000
- **Cause**: Earthquake + tsunami
- **Region**: Strait of Messina, Italy

**3. LISBON 1755** 🇵🇹
- **Deaths**: 50,000-100,000
- **Cause**: Magnitude 8.5-9.0 earthquake
- **Particularity**: All Saints' Day

**4. KRAKATOA 1883** 🌋
- **Deaths**: 36,000
- **Cause**: Volcanic eruption
- **Waves**: Up to 40m

**5. NANKAI 1498** 🇯🇵
- **Deaths**: 31,000
- **Cause**: Magnitude 8.6 earthquake
- **Region**: Southern Japan coast

**6. TOHOKU 2011** 🇯🇵
- **Deaths**: 18,000
- **Cause**: Magnitude 9.0 earthquake
- **Particularity**: Nuclear accident

**7. PAPUA 1998** 🇵🇬
- **Deaths**: 2,200
- **Cause**: Earthquake + landslide
- **Waves**: 15m

**TRENDS:**
- Increasing victims with coastal density
- Recent reduction thanks to warning systems
- Growing importance of preparation
            """,
            "ar": """
**📜 أخطر تسونامي في التاريخ**

**التصنيف التاريخي:**

**1. المحيط الهندي 2004** 🌊
- **الوفيات**: 230,000-280,000
- **السبب**: زلزال قوة 9.1
- **الدول**: 14 دولة متضررة

**2. ميسينا 1908** 🇮🇹
- **الوفيات**: 123,000
- **السبب**: زلزال + تسونامي
- **المنطقة**: مضيق ميسينا، إيطاليا

**3. لشبونة 1755** 🇵🇹
- **الوفيات**: 50,000-100,000
- **السبب**: زلزال قوة 8.5-9.0
- **الخصوصية**: يوم جميع القديسين

**4. كراكاتوا 1883** 🌋
- **الوفيات**: 36,000
- **السبب**: ثوران بركاني
- **الأمواج**: حتى 40م

**5. نانكاي 1498** 🇯🇵
- **الوفيات**: 31,000
- **السبب**: زلزال قوة 8.6
- **المنطقة**: الساحل الجنوبي لليابان

**6. توهوكو 2011** 🇯🇵
- **الوفيات**: 18,000
- **السبب**: زلزال قوة 9.0
- **الخصوصية**: حادث نووي

**7. بابوا 1998** 🇵🇬
- **الوفيات**: 2,200
- **السبب**: زلزال + انهيار أرضي
- **الأمواج**: 15م

**الاتجاهات:**
- زيادة الضحايا مع الكثافة الساحلية
- انخفاض حديث بفضل أنظمة الإنذار
- أهمية متزايدة للاستعداد
            """
        }
    },
    
    "pays_affectes_tsunamis": {
        "keywords": {
            "fr": ["pays affectés", "différents pays", "pays touchés", "régions affectées"],
            "en": ["affected countries", "different countries", "countries affected", "affected regions"],
            "ar": ["دول متضررة", "دول مختلفة", "دول تأثرت", "مناطق متضررة"]
        },
        "responses": {
            "fr": """
**🌍 COMMENT DIFFÉRENTS PAYS ONT ÉTÉ AFFECTÉS PAR DES TSUNAMIS CÉLÈBRES**

**JAPON 🇯🇵**
- **Fréquence** : Très élevée (situé sur la ceinture de feu)
- **Expérience** : Culture de préparation séculaire
- **Exemple 2011** : 18,000 morts malgré les systèmes avancés
- **Spécificité** : Technologies d'alerte les plus avancées au monde

**INDONÉSIE 🇮🇩**
- **Risque** : Très élevé (convergence de plaques)
- **Tsunami 2004** : 170,000 morts à Aceh seul
- **Tsunami 2018** : Palu (causé par glissement terrain)
- **Défis** : Archipel avec populations côtières denses

**CHILI 🇨🇱**
- **Caractéristique** : Longue côte sismique
- **1960** : Plus grand séisme enregistré (9.5)
- **2010** : Tsunami après séisme de 8.8
- **Stratégie** : Évacuations préventives massives

**ÉTATS-UNIS 🇺🇸**
- **Régions à risque** : Côte ouest, Hawaii, Alaska
- **1964** : Tsunami du Alaska affectant la Californie
- **Hawaii** : Régulièrement touché par des tsunamis trans-pacifiques
- **Systèmes** : PTWC (Pacific Tsunami Warning Center)

**THAÏLANDE 🇹🇭**
- **2004** : 8,000 morts, surtout des touristes
- **Impact** : Dévastation du secteur touristique
- **Leçons** : Développement de systèmes d'alerte

**SRI LANKA 🇱🇰**
- **2004** : 35,000 morts
- **Particularité** : Aucun antécédent de tsunami dans la mémoire collective
- **Réponse** : Reconstruction avec assistance internationale

**ITALIE 🇮🇹**
- **1908** : Détroit de Messine (123,000 morts)
- **Risque** : Principalement Méditerranée
- **Systèmes** : Système d'alerte pour la Méditerranée

**PORTUGAL 🇵🇹**
- **1755** : Lisbonne, un des tsunamis les plus étudiés
- **Impact historique** : Influence sur la philosophie européenne
- **Préparation** : Systèmes modernes d'alerte
            """,
            "en": """
**🌍 HOW DIFFERENT COUNTRIES WERE AFFECTED BY FAMOUS TSUNAMIS**

**JAPAN 🇯🇵**
- **Frequency**: Very high (located on ring of fire)
- **Experience**: Centuries-old preparation culture
- **2011 example**: 18,000 deaths despite advanced systems
- **Specificity**: World's most advanced warning technologies

**INDONESIA 🇮🇩**
- **Risk**: Very high (plate convergence)
- **2004 tsunami**: 170,000 deaths in Aceh alone
- **2018 tsunami**: Palu (caused by landslide)
- **Challenges**: Archipelago with dense coastal populations

**CHILE 🇨🇱**
- **Characteristic**: Long seismic coast
- **1960**: Largest recorded earthquake (9.5)
- **2010**: Tsunami after 8.8 earthquake
- **Strategy**: Massive preventive evacuations

**UNITED STATES 🇺🇸**
- **Risk regions**: West coast, Hawaii, Alaska
- **1964**: Alaska tsunami affecting California
- **Hawaii**: Regularly affected by trans-Pacific tsunamis
- **Systems**: PTWC (Pacific Tsunami Warning Center)

**THAILAND 🇹🇭**
- **2004**: 8,000 deaths, mostly tourists
- **Impact**: Devastation of tourism sector
- **Lessons**: Development of warning systems

**SRI LANKA 🇱🇰**
- **2004**: 35,000 deaths
- **Particularity**: No tsunami precedent in collective memory
- **Response**: Reconstruction with international assistance

**ITALY 🇮🇹**
- **1908**: Strait of Messina (123,000 deaths)
- **Risk**: Mainly Mediterranean
- **Systems**: Mediterranean warning system

**PORTUGAL 🇵🇹**
- **1755**: Lisbon, one of most studied tsunamis
- **Historical impact**: Influence on European philosophy
- **Preparation**: Modern warning systems
            """,
            "ar": """
**🌍 كيف تأثرت دول مختلفة بتسونامي مشهورة**

**اليابان 🇯🇵**
- **التكرار**: عالي جدًا (تقع على حزام النار)
- **الخبرة**: ثقافة استعداد عمرها قرون
- **مثال 2011**: 18,000 وفاة رغم الأنظمة المتقدمة
- **الخصوصية**: أكثر تكنولوجيات الإنذار تقدمًا في العالم

**إندونيسيا 🇮🇩**
- **الخطر**: عالي جدًا (تقارب الصفائح)
- **تسونامي 2004**: 170,000 وفاة في آتشيه وحدها
- **تسونامي 2018**: بالو (سببها انهيار أرضي)
- **التحديات**: أرخبيل بكثافات ساحلية عالية

**تشيلي 🇨🇱**
- **الخاصية**: ساحل زلزالي طويل
- **1960**: أكبر زلزال مسجل (9.5)
- **2010**: تسونامي بعد زلزال 8.8
- **الاستراتيجية**: إخلاءات وقائية جماعية

**الولايات المتحدة 🇺🇸**
- **مناطق الخطر**: الساحل الغربي، هاواي، ألاسكا
- **1964**: تسونامي ألاسكا أثر على كاليفورنيا
- **هاواي**: تتأثر بانتظام بتسونامي عابرة للمحيط الهادئ
- **الأنظمة**: PTWC (مركز إنذار تسونامي المحيط الهادئ)

**تايلاند 🇹🇭**
- **2004**: 8,000 وفاة، معظمهم سياح
- **التأثير**: تدمير قطاع السياحة
- **الدروس**: تطوير أنظمة الإنذار

**سريلانكا 🇱🇰**
- **2004**: 35,000 وفاة
- **الخصوصية**: لا سابقة لتسونامي في الذاكرة الجماعية
- **الاستجابة**: إعادة إعمار بمساعدة دولية

**إيطاليا 🇮🇹**
- **1908**: مضيق ميسينا (123,000 وفاة)
- **الخطر**: mainly Mediterranean
- **الأنظمة**: نظام إنذار للبحر المتوسط

**البرتغال 🇵🇹**
- **1755**: لشبونة، من أكثر تسونامي studied
- **التأثير التاريخي**: تأثير على الفلسفة الأوروبية
- **الاستعداد**: أنظمة إنذار حديثة
            """
        }
    }
}

# ==================== FONCTION DE RECHERCHE AMÉLIORÉE ====================

def find_response(user_input, language):
    """Trouve la réponse la plus pertinente avec reconnaissance améliorée"""
    user_input_lower = user_input.lower()
    
    # Recherche améliorée - vérifie chaque mot-clé individuellement
    best_match = None
    best_score = 0
    
    for category, data in KNOWLEDGE_BASE.items():
        score = 0
        for keyword in data["keywords"][language]:
            if keyword in user_input_lower:
                score += 1
        
        if score > best_score:
            best_score = score
            best_match = category
    
    # Si on a trouvé une bonne correspondance
    if best_score >= 1:
        return KNOWLEDGE_BASE[best_match]["responses"][language]
    
    # Recherche de secours avec mots individuels
    for category, data in KNOWLEDGE_BASE.items():
        for keyword in data["keywords"][language]:
            # Vérifie si des mots individuels correspondent
            words = user_input_lower.split()
            for word in words:
                if word in keyword or keyword in word:
                    return data["responses"][language]
    
    # Réponse par défaut
    default_responses = {
        "fr": "🤖 **Expert Tsunami** - Je n'ai pas compris votre question. Essayez avec : définition, causes, séisme, volcan, conséquences, ou signes avant-coureurs.",
        "en": "🤖 **Tsunami Expert** - I didn't understand your question. Try with: definition, causes, earthquake, volcano, consequences, or warning signs.",
        "ar": "🤖 **خبير التسونامي** - لم أفهم سؤالك. جرب مع: تعريف، أسباب، زلزال، بركان، عواقب، أو علامات إنذار."
    }
    return default_responses[language]

def display_text(text, language):
    """Affiche le texte avec la bonne direction"""
    if language == "ar":
        st.markdown(f'<div class="arabic-text">{text}</div>', unsafe_allow_html=True)
    else:
        st.markdown(text)

# ==================== INTERFACE ====================

# Titre
st.markdown('<div class="main-header">🌊 Expert Tsunami</div>', unsafe_allow_html=True)

# Sidebar
with st.sidebar:
    st.markdown("### 🌍 Langue")
    selected_language = st.radio("", list(LANGUAGES.keys()), label_visibility="collapsed")
    current_lang = LANGUAGES[selected_language]
    
    # Questions par catégorie
    categories = {
        "fr": {
            "definition": "📚 Définition et Causes",
            "consequences": "💥 Conséquences",
            "historique": "📜 Exemples Historiques"
        },
        "en": {
            "definition": "📚 Definition and Causes", 
            "consequences": "💥 Consequences",
            "historique": "📜 Historical Examples"
        },
        "ar": {
            "definition": "📚 التعريف والأسباب",
            "consequences": "💥 العواقب",
            "historique": "📜 أمثلة تاريخية"
        }
    }
    
    questions_by_category = {
        "definition": {
            "fr": [
                "Qu'est-ce qu'un tsunami ?",
                "Différence avec vague normale", 
                "Causes principales",
                "Comment un séisme provoque un tsunami",
                "Tsunamis volcaniques et glissements",
                "Signes avant-coureurs"
            ],
            "en": [
                "What is a tsunami?",
                "Difference with normal wave",
                "Main causes",
                "How earthquake causes tsunami", 
                "Volcanic and landslide tsunamis",
                "Warning signs"
            ],
            "ar": [
                "ما هو التسونامي؟",
                "الفرق مع الموجة العادية",
                "الأسباب الرئيسية",
                "كيف يتسبب الزلزال في تسونامي",
                "تسونامي البراكين والانهيارات", 
                "علامات الإنذار"
            ]
        },
        "consequences": {
            "fr": [
                "Conséquences humaines",
                "Impacts économiques",
                "Impacts environnementaux",
                "Exemples de dégâts importants",
                "Effets à long terme",
                "Mortalité moyenne"
            ],
            "en": [
                "Human consequences", 
                "Economic impacts",
                "Environmental impacts",
                "Examples of significant damage",
                "Long-term effects",
                "Average mortality"
            ],
            "ar": [
                "العواقب البشرية",
                "الآثار الاقتصادية",
                "الآثار البيئية",
                "أمثلة على أضرار كبيرة",
                "الآثار طويلة الأجل",
                "متوسط الوفيات"
            ]
        },
        "historique": {
            "fr": [
                "Tsunami de 2004",
                "Tsunami du Japon 2011",
                "Tsunamis les plus meurtriers",
                "Pays affectés par des tsunamis"
            ],
            "en": [
                "2004 tsunami",
                "2011 Japan tsunami",
                "Deadliest tsunamis",
                "Countries affected by tsunamis"
            ],
            "ar": [
                "تسونامي 2004",
                "تسونامي اليابان 2011",
                "أخطر تسونامي",
                "دول تأثرت بتسونامي"
            ]
        }
    }
    
    for category_key, category_name in categories[current_lang].items():
        st.markdown(f'<div class="category-header">{category_name}</div>', unsafe_allow_html=True)
        for question in questions_by_category[category_key][current_lang]:
            if st.button(question, key=f"{category_key}_{question}"):
                st.session_state.auto_question = question
    
    st.markdown("---")
    st.markdown("### 🚨 Urgence")
    emergency_texts = {
        "fr": ["Éloignement immédiat", "112 • 911 • 999"],
        "en": ["Immediate evacuation", "112 • 911 • 999"],
        "ar": ["إخلاء فوري", "112 • 911 • 999"]
    }
    st.markdown(f"**{emergency_texts[current_lang][0]}**")
    st.markdown(f"**{emergency_texts[current_lang][1]}**")

# Zone de chat
st.markdown('<div class="chat-container">', unsafe_allow_html=True)

# Historique de conversation
if "messages" not in st.session_state:
    welcome_messages = {
        "fr": "🌊 **Expert Tsunami** - Je peux répondre à vos questions sur : définition, causes, conséquences des tsunamis. Utilisez les boutons ou tapez vos questions !",
        "en": "🌊 **Tsunami Expert** - I can answer your questions about: definition, causes, consequences of tsunamis. Use buttons or type your questions!", 
        "ar": "🌊 **خبير التسونامي** - يمكنني الإجابة على أسئلتك عن: تعريف، أسباب، عواقب التسونامي. استخدم الأزرار أو اكتب أسئلتك!"
    }
    st.session_state.messages = [
        {"role": "assistant", "content": welcome_messages[current_lang]}
    ]

# Affichage de l'historique
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        display_text(message["content"], current_lang)

# Gestion des questions automatiques
if "auto_question" in st.session_state:
    prompt = st.session_state.auto_question
    del st.session_state.auto_question
else:
    prompt = None

# Input utilisateur
placeholder_texts = {
    "fr": "💬 Posez votre question...",
    "en": "💬 Ask your question...", 
    "ar": "💬 اطرح سؤالك..."
}

if prompt or (user_input := st.chat_input(placeholder_texts[current_lang])):
    
    if not prompt:
        prompt = user_input
    
    # Ajout du message utilisateur
    st.session_state.messages.append({"role": "user", "content": prompt})
    
    # Génération de la réponse
    response = find_response(prompt, current_lang)
    
    # Ajout de la réponse
    st.session_state.messages.append({
        "role": "assistant", 
        "content": response
    })
    
    st.rerun()

st.markdown('</div>', unsafe_allow_html=True)
