import streamlit as st
import random
import base64
from PIL import Image

# Configuration de la page
st.set_page_config(page_title="🌍 TsunamiGuard Pro", page_icon="🌊", layout="wide")

# ==================== SYSTÈME MULTILINGUE ====================

LANGUAGES = {
    "Français": "fr",
    "English": "en", 
    "العربية": "ar"
}

# Dictionnaire multilingue
MULTILINGUAL_KNOWLEDGE = {
    "fr": {
        "tsunami": {
            "definition": "🌊 **Un tsunami** est une série de vagues océaniques extrêmement longues générées par le déplacement soudain d'un grand volume d'eau.",
            "details": "Les tsunamis peuvent voyager à 800 km/h en eau profonde et atteindre 30m de haut près des côtes."
        },
        "welcome": "🌊 Bonjour ! Je suis Expert TsunamiGuard. Je peux vous renseigner sur les tsunamis, la sécurité et l'apport de la géomatique.",
        "suggested_questions": "💡 Questions suggérées",
        "emergency": "📞 Urgence"
    },
    "en": {
        "tsunami": {
            "definition": "🌊 **A tsunami** is a series of extremely long ocean waves generated by the sudden displacement of a large volume of water.",
            "details": "Tsunamis can travel at 800 km/h in deep water and reach 30m high near coasts."
        },
        "welcome": "🌊 Hello! I am TsunamiGuard Expert. I can inform you about tsunamis, safety, and geomatics applications.",
        "suggested_questions": "💡 Suggested Questions", 
        "emergency": "📞 Emergency"
    },
    "ar": {
        "tsunami": {
            "definition": "🌊 **تسونامي** هو سلسلة من أمواج المحيط الطويلة جدًا الناتجة عن الانزياح المفاجئ لحجم كبير من الماء.",
            "details": "يمكن أن تنتقل أمواج التسونامي بسرعة 800 كم/ساعة في المياه العميقة وتصل إلى 30 مترًا بالقرب من السواحل."
        },
        "welcome": "🌊 مرحبًا! أنا خبير تسونامي جارد. يمكنني إطلاعك على أمواج التسونامي والسلامة وتطبيقات الجيوماتكس.",
        "suggested_questions": "💡 الأسئلة المقترحة",
        "emergency": "📞 الطوارئ"
    }
}

# ==================== BASE DE CONNAISSANCES AVANCÉE ====================

KNOWLEDGE_BASE = {
    "tsunami": {
        "keywords": ["tsunami", "موجة", "wave", "تسونامي"],
        "responses": {
            "fr": "🌊 **Un tsunami** est une série de vagues océaniques extrêmement longues. Vitesse: 800 km/h, Hauteur: jusqu'à 30m.",
            "en": "🌊 **A tsunami** is a series of extremely long ocean waves. Speed: 800 km/h, Height: up to 30m.", 
            "ar": "🌊 **تسونامي** هو سلسلة من أمواج المحيط الطويلة جدًا. السرعة: 800 كم/ساعة، الارتفاع: حتى 30 مترًا."
        }
    },
    "causes": {
        "keywords": ["cause", "provoque", "سبب", "origin", "why", "لماذا"],
        "responses": {
            "fr": "📌 **Causes principales :**\n• Séismes sous-marins (90%)\n• Glissements de terrain\n• Éruptions volcaniques\n• Impacts de météorites",
            "en": "📌 **Main causes:**\n• Undersea earthquakes (90%)\n• Landslides\n• Volcanic eruptions\n• Meteorite impacts",
            "ar": "📌 **الأسباب الرئيسية:**\n• الزلازل تحت البحر (90٪)\n• الانهيارات الأرضية\n• الثورات البركانية\n• تأثيرات النيازك"
        }
    },
    "safety": {
        "keywords": ["sécurité", "safety", "أمان", "danger", "خطر", "que faire", "what to do", "ماذا أفعل"],
        "responses": {
            "fr": "🛡️ **5 RÈGLES D'OR :**\n1. Éloignez-vous du rivage\n2. Gagnez les hauteurs (>15m)\n3. Ne prenez pas la voiture\n4. Ne retournez pas\n5. Restez informé",
            "en": "🛡️ **5 GOLDEN RULES:**\n1. Move away from shore\n2. Reach high ground (>15m)\n3. Don't take car\n4. Don't go back\n5. Stay informed", 
            "ar": "🛡️ **5 قواعد ذهبية:**\n1. ابتعد عن الشاطئ\n2. اتجه إلى المرتفعات (>15م)\n3. لا تستخدم السيارة\n4. لا تعود\n5. ابق على اطلاع"
        }
    },
    "geomatics": {
        "keywords": ["géomatique", "geomatics", "جيوماتكس", "SIG", "GIS", "cartographie", "mapping", "خرائط"],
        "responses": {
            "fr": "🗺️ **Rôle de la géomatique :**\n• Cartographie des risques\n• Modélisation SIG\n• Plans d'évacuation\n• Surveillance temps réel",
            "en": "🗺️ **Geomatics role:**\n• Risk mapping\n• GIS modeling\n• Evacuation plans\n• Real-time monitoring",
            "ar": "🗺️ **دور الجيوماتكس:**\n• رسم خرائط المخاطر\n• نمذجة نظم المعلومات الجغرافية\n• خطط الإخلاء\n• المراقبة في الوقت الحقيقي"
        }
    }
}

# ==================== FONCTIONS INTELLIGENTES ====================

def get_best_response(user_input, language):
    """Trouve la meilleure réponse basée sur les mots-clés"""
    user_input = user_input.lower()
    
    # Recherche par mots-clés
    for topic, data in KNOWLEDGE_BASE.items():
        for keyword in data["keywords"]:
            if keyword.lower() in user_input:
                return data["responses"][language]
    
    # Réponses par défaut selon la langue
    default_responses = {
        "fr": [
            "🌊 Posez-moi des questions sur: causes, sécurité, ou géomatique!",
            "🤔 Essayez: 'Que faire en cas de tsunami?' ou 'Rôle de la géomatique?'"
        ],
        "en": [
            "🌊 Ask me about: causes, safety, or geomatics!",
            "🤔 Try: 'What to do in tsunami?' or 'Geomatics role?'"
        ],
        "ar": [
            "🌊 اسألني عن: الأسباب، السلامة، أو الجيوماتكس!",
            "🤔 جرب: 'ماذا أفعل في التسونامي؟' أو 'دور الجيوماتكس؟'"
        ]
    }
    
    return random.choice(default_responses[language])

def display_media(media_type):
    """Affiche images ou vidéos éducatives"""
    if media_type == "tsunami_diagram":
        st.image("https://i.imgur.com/abc123.png", caption="Schéma de formation d'un tsunami")
    elif media_type == "evacuation_map":
        st.image("https://i.imgur.com/xyz789.png", caption="Carte d'évacuation type")

def get_suggested_questions(language):
    """Retourne les questions suggérées selon la langue"""
    questions = {
        "fr": [
            "Qu'est-ce qu'un tsunami?",
            "Que faire en cas d'alerte?",
            "Rôle de la géomatique?",
            "Causes principales?"
        ],
        "en": [
            "What is a tsunami?",
            "What to do in alert?",
            "Geomatics role?",
            "Main causes?"
        ],
        "ar": [
            "ما هو التسونامي؟",
            "ماذا أفعل في حالة الإنذار؟",
            "دور الجيوماتكس؟",
            "الأسباب الرئيسية؟"
        ]
    }
    return questions[language]

# ==================== INTERFACE STREAMLIT ====================

# Sidebar pour la sélection de langue
with st.sidebar:
    st.header("🌍 Language / اللغة")
    selected_language = st.radio("Choisir la langue / Select language / اختر اللغة", 
                               list(LANGUAGES.keys()))
    
    current_lang = LANGUAGES[selected_language]
    
    st.header(MULTILINGUAL_KNOWLEDGE[current_lang]["suggested_questions"])
    for question in get_suggested_questions(current_lang):
        st.write(f"• {question}")
    
    st.header(MULTILINGUAL_KNOWLEDGE[current_lang]["emergency"])
    st.markdown("**112** (Europe) / **911** (US) / **999** (UK)")

# Interface principale
st.title("🌍 TsunamiGuard Pro - Multilingual Expert")
st.markdown("**Chatbot expert en tsunamis, sécurité et géomatique**")

# Section médias
with st.expander("📸 **Médias éducatifs / Educational Media / الوسائط التعليمية**"):
    col1, col2 = st.columns(2)
    with col1:
        st.write("**Diagramme de formation / Formation diagram / مخطط التشكيل**")
        # Lien vers image éducative
        st.markdown("[📊 Voir le diagramme](https://example.com/tsunami-diagram)")
    with col2:
        st.write("**Vidéo éducative / Educational video / فيديو تعليمي**")
        # Lien vers vidéo YouTube éducative
        st.markdown("[🎥 Regarder la vidéo](https://youtube.com/tsunami-education)")

# Historique de conversation
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": MULTILINGUAL_KNOWLEDGE[current_lang]["welcome"]}
    ]

# Affichage de l'historique
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        # Support pour l'arabe (alignement à droite)
        if current_lang == "ar":
            st.markdown(f"<div dir='rtl' style='text-align: right;'>{message['content']}</div>", unsafe_allow_html=True)
        else:
            st.markdown(message["content"])

# Zone de saisie
if prompt := st.chat_input(f"Posez votre question / Ask your question / اطرح سؤالك..."):
    # Ajout du message utilisateur
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        if current_lang == "ar":
            st.markdown(f"<div dir='rtl' style='text-align: right;'>{prompt}</div>", unsafe_allow_html=True)
        else:
            st.markdown(prompt)
    
    # Génération de la réponse intelligente
    response = get_best_response(prompt, current_lang)
    
    # Ajout de la réponse
    st.session_state.messages.append({"role": "assistant", "content": response})
    with st.chat_message("assistant"):
        if current_lang == "ar":
            st.markdown(f"<div dir='rtl' style='text-align: right;'>{response}</div>", unsafe_allow_html=True)
        else:
            st.markdown(response)

# Footer informatif
st.markdown("---")
st.markdown("🔬 *Développé par des étudiants en géoinformatique - Projet éducatif*")

# Section d'information rapide
st.sidebar.markdown("---")
st.sidebar.info(
    "💡 **Conseil:** Utilisez des mots-clés comme 'sécurité', 'causes', "
    "'géomatique' pour des réponses précises."
)
